################################################################
## Packages / Pi-Hole
## #!secret_example
#pi_hole_url: http://freaksecurity.duckdns.org:8080/admin/api.php
#Authorization & Token required (see WEBPASSWORD in /etc/pihole/setupVars.conf)
#pi_hole_switch_on: /usr/bin/curl -k "localhost/admin/api.php?enable&auth=webkey"
#pi_hole_switch_off: /usr/bin/curl -k "localhost/admin/api.php?disable=600&auth=webkey"
# the .SH file I am using is here
#https://github.com/Norien/Home-Assistant-Config/blob/master/shell/pihole.sh
################################################################
homeassistant:
  customize:
    sensor.ads_percentage_today:
      friendly_name: Porcentaje de Trafico de Anuncios Bloqueados
      unit_of_measurement: '%'
      icon: mdi:ticket-percent

    sensor.domains_being_blocked:
      friendly_name: Total de dominios bloqueados
      icon: mdi:do-not-disturb

    sensor.ads_blocked_today:
      friendly_name: Anuncios Bloqueados Hoy
      icon: mdi:do-not-disturb

    sensor.dns_queries_today:
      friendly_name: DNS Queries de Hoy
      icon: mdi:note-text

    sensor.unique_domains:
      friendly_name: Dominios Unicos
      icon: mdi:approval

    sensor.queries_forwarded:
      friendly_name: Queries Forwarded
      icon: mdi:arrange-send-backward

    sensor.queries_cached:
      friendly_name: Queries Cacheadas
      icon: mdi:animation

    sensor.pi_hole_version:
      friendly_name: Version

    sensor.pihole_status_raw:
      hidden: true

group:
  Pi Hole:
    entities:
      - sensor.ads_blocked_today
      - sensor.ads_percentage_today
      - sensor.dns_queries_today
      - sensor.domains_being_blocked
      - sensor.ads_blocked_today
      - sensor.unique_domains
      - sensor.queries_forwarded
      - sensor.queries_cached
      - sensor.pi_hole_version
      - script.pihole_update

###############################################################################
#  Sensors
###############################################################################
sensor:
  - platform: rest
    name: dns_queries_today
    resource: !secret pi_hole_url
    value_template: '{{ value_json.dns_queries_today }}'

  - platform: rest
    name: domains_being_blocked
    resource: !secret pi_hole_url
    value_template: '{{ value_json.domains_being_blocked }}'

  - platform: rest
    name: ads_blocked_today
    resource: !secret pi_hole_url
    value_template: '{{ value_json.ads_blocked_today }}'

  - platform: rest
    name: ads_percentage_today
    resource: !secret pi_hole_url
    value_template: '{{ value_json.ads_percentage_today | int }}'

  - platform: rest
    name: unique_domains
    resource: !secret pi_hole_url
    value_template: '{{ value_json.unique_domains }}'

  - platform: rest
    name: queries_forwarded
    resource: !secret pi_hole_url
    value_template: '{{ value_json.queries_forwarded }}'

  - platform: rest
    name: queries_cached
    resource: !secret pi_hole_url
    value_template: '{{ value_json.queries_cached }}'
